export const featureCardData = [
    {
      title: "Add a Fixed Fee",
      description: "Apply a standard, fixed fee for every COD order to cover processing costs.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Add a Fixed Fee",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Add a Fee Based on Cart Value",
      description: "Set dynamic COD fees that increase or decrease based on the total cart value.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Add a Fee Based on Cart Value",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Add a Fee Based on Cart Weight",
      description: "Charge COD fees that vary according to the total weight of the items in the cart.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Add a Fee Based on Cart Weight",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Restrict COD for Low and High Order Value Orders",
      description: "Block COD for orders that fall below a set minimum value or high value.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Restrict COD for Low and High Order Value Orders",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Pincode",
      description: "Restrict or allow COD availability based on specific postal codes.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Pincode",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "State",
      description: "Support Manage COD access at the state level to align with your delivery capabilities.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "State",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Country",
      description: "Enable or disable COD by country, ensuring it’s only offered in regions where it’s practical.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Country",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Specific Product",
      description: "Offer COD only for selected products that are ideal for cash on delivery.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Specific Product",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Specific Collection",
      description: "Allow COD for entire product collections, streamlining availability for groups of items.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Specific Collection",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Product Tag",
      description: "Set COD availability based on product tags, allowing more granular control.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Product Tag",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Product Variant",
      description: "Control COD based on specific product variants, like size or color.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Product Variant",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Product Handle",
      description: "Manage COD rules for products identified by unique handles.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Product Handle",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Product Vendor",
      description: "Allow or restrict COD based on the product’s vendor or supplier.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Product Vendor",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Customer Tag",
      description: "Restrict or allow COD for customers tagged with specific criteria.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Customer Tag",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Customer Email",
      description: "Offer COD only to customers with verified or trusted email addresses.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Customer Email",
      imageWidth: 400,
      imageHeight: 300,
    },
    {
      title: "Customer Phone Number",
      description: "Manage COD eligibility based on the customer’s phone number.",
      imageSrc: "/images/features/features-light-01.png",
      imageAlt: "Customer Phone Number",
      imageWidth: 400,
      imageHeight: 300,
    },
  ];
  