export const groupedFeatureSections = [
  {
    sectionType: "COD Fee Options",
    heading: "Manage Your COD Fee Strategies",
    paragraph: "Choose from various COD fee structures to optimize your business processes and cost management.",
    features: [
      {
        title: "Add a Fixed Fee",
        description: "Apply a standard, fixed fee for every COD order to cover processing costs.",
        imageSrc: "/images/features/add-cash-on-delivery.png",
        imageAlt: "Add a Fixed Fee",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Add a Fee Based on Cart Value",
        description: "Set dynamic COD fees that increase or decrease based on the total cart value.",
        imageSrc: "/images/features/add-cash-on-delivery-based-on-cart-total.png",
        imageAlt: "Add a Fee Based on Cart Value",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Add a Fee Based on Cart Weight",
        description: "Charge COD fees that vary according to the total weight of the items in the cart.",
        imageSrc: "/images/features/add-cash-on-delivery-based-on-cart-weight.png",
        imageAlt: "Add a Fee Based on Cart Weight",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Restrict COD for Low and High Value ",
        description: "Block COD for orders that fall below a set minimum value or high value.",
        imageSrc: "/images/features/Restrict cod-for-low-and-high-order-value-orders.png",
        imageAlt: "Restrict COD for Low and High Order Value Orders",
        imageWidth: 400,
        imageHeight: 300,
      },
    ],
  },
  {
    sectionType: "Location-Based Restrictions",
    heading: "Control COD Availability by Location",
    paragraph: "Restrict or manage COD options based on different location parameters.",
    features: [
      {
        title: "Pincode",
        description: "Restrict or allow COD availability based on specific postal codes.",
        imageSrc: "/images/features/enable-disable-cod-by-pin-code.png",
        imageAlt: "Pincode",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "State",
        description: "Manage COD access at the state level to align with your delivery capabilities.",
        imageSrc: "/images/features/enable-disable-cod-by-state.png",
        imageAlt: "State",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Country",
        description: "Enable or disable COD by country, ensuring it’s only offered in regions where it’s practical.",
        imageSrc: "/images/features/enable-disable-cod-by-country.png",
        imageAlt: "Country",
        imageWidth: 400,
        imageHeight: 300,
      },
    ],
  },
  {
    sectionType: "Product-Based Restrictions",
    heading: "Offer COD Based on Product Specifics",
    paragraph: "Customize COD availability for specific products or product collections.",
    features: [
      {
        title: "Specific Product",
        description: "Offer COD only for selected products that are ideal for cash on delivery.",
        imageSrc: "/images/features/enable-disable-cod-by-product.png",
        imageAlt: "Specific Product",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Specific Collection",
        description: "Allow COD for entire product collections, streamlining availability for groups of items.",
        imageSrc: "/images/features/enable-disable-cod-by-collection.png",
        imageAlt: "Specific Collection",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Product Tag",
        description: "Set COD availability based on product tags, allowing more granular control.",
        imageSrc: "/images/features/enable-disable-cod-by-product-tag.png",
        imageAlt: "Product Tag",
        imageWidth: 400,
        imageHeight: 300,
      },
      
    ],
  },
  {
    sectionType: "Customer-Based Restrictions",
    heading: "Manage COD Eligibility by Customer Details",
    paragraph: "Control COD options based on customer-specific attributes.",
    features: [
      {
        title: "Customer Tag",
        description: "Restrict or allow COD for customers tagged with specific criteria.",
        imageSrc: "/images/features/enable-disable-cod-by-customer-tag.png",
        imageAlt: "Customer Tag",
        imageWidth: 400,
        imageHeight: 300,
      },
     
    ],
  },
  {
    sectionType: "Discount-Based Restrictions",
    heading: "Control COD Based on Discounts",
    paragraph: "Manage Cash on Delivery options based on discount conditions to minimize risks and optimize profits.",
    features: [
      {
        title: "Enable/Disable COD Based on Discount Amount",
        description: "Allow or restrict COD when the discount amount exceeds or falls below a specified limit.",
        imageSrc: "/images/features/enable-disable-cod-by-discount-amount.png",
        imageAlt: "Enable COD Based on Discount Amount",
        imageWidth: 400,
        imageHeight: 300,
      },
      {
        title: "Enable/Disable COD If Any Discount Is Applied",
        description: "Automatically disable or enable COD when any discount is applied to the cart.",
        imageSrc: "/images/features/enable-disable-cod-by-discount-applied.png",
        imageAlt: "Enable COD If Discount Applied",
        imageWidth: 400,
        imageHeight: 300,
      },
    ],
  },
];
